# Generated by Django 4.1 on 2023-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('creation_date', models.DateField()),
                ('writing_language', models.SmallIntegerField(choices=[(1, 'English'), (2, 'German')])),
                ('additional_information', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
