# Generated by Django 4.1 on 2023-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
