# Generated by Django 4.1 on 2023-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentForum', '0002_alter_post_creation_date_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_information',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
