# Generated by Django 4.2.7 on 2024-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentForum', '0004_alter_post_author_alter_post_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writing_language',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German')]),
        ),
    ]
