# Generated by Django 4.2.7 on 2023-11-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='institutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThesisListing.departments')),
            ],
        ),
        migrations.CreateModel(
            name='thesis_listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1000)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('writing_language', models.SmallIntegerField(choices=[(1, 'English'), (2, 'German')])),
                ('student_level', models.SmallIntegerField(choices=[(1, 'Bachelor'), (2, 'Master'), (3, 'Phd'), (4, 'Open to all levels')])),
                ('additional_information', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThesisListing.departments')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThesisListing.institutes')),
            ],
        ),
    ]
