# Generated by Django 4.2.7 on 2023-11-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisListing', '0003_initial_data_institutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis_listings',
            name='student_level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd'), ('Open to all levels', 'Open to all levels')]),
        ),
        migrations.AlterField(
            model_name='thesis_listings',
            name='writing_language',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German')]),
        ),
    ]
