# Generated by Django 4.2.7 on 2023-12-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisListing', '0004_alter_thesis_listings_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis_listings',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thesis_listings',
            name='supervisor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='thesis_listings',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
