# Generated by Django 4.2.7 on 2024-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisListing', '0005_alter_thesis_listings_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis_listings',
            name='field_name',
            field=models.FileField(blank=True, max_length=254, upload_to=None),
        ),
    ]
